Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 20

AllCops:
  TargetRubyVersion: "2.6.3"
  Exclude:
    - jdoodle.gemspec